[package]
name = "polars-tdms-core"
version = "0.1.0"
edition = "2021"
description = "Rust core (PyO3) for the polars-tdms IO extension"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
tdms-rs = { git = "https://github.com/szst11/tdms-rs.git", rev = "765c7fbc590aad3a3d87a47dd8696cd7ad5f95d0" }

[profile.release]
lto = "thin"
codegen-units = 1
