[package]
name = "polars-tdms-core"
version = "0.1.0"
edition = "2021"
description = "Rust core (PyO3) for the polars-tdms IO extension"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
tdms-rs = { git = "https://github.com/szst11/tdms-rs.git", rev = "6e61f0e888bed4b7bf2a93b978d57e95e8a7cbbb" }

[profile.release]
lto = "thin"
codegen-units = 1
